---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pauls-guestbook
spec:
  syncPolicy:
    automated: # automated sync by default retries failed attempts 5 times with following delays between attempts ( 5s, 10s, 20s, 40s, 80s ); retry controlled using `retry` field.
      prune: true # Specifies if resources should be pruned during auto-syncing ( false by default ).
      selfHeal: true # Specifies if partial app sync should be executed when resources are changed only in target Kubernetes cluster and no git change detected ( false by default ).
    syncOptions:     # Sync options which modifies sync behavior
    - Validate=false # disables resource validation (equivalent to 'kubectl apply --validate=true')
    retry:
      limit: 5 # number of failed sync attempt retries
      backoff:
        duration: 5s # the amount to back off.
        factor: 2 # a factor to multiply the base duration
        maxDuration: 3m # the maximum backoff of time
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    path: guestbook
    repoURL: https://github.com/gfthybridlabs/argocd.git
