apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bookinfo-app
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: anthos
  source:
    path: bookinfo-app
    repoURL: https://github.com/gfthybridlabs/argocd.git
    targetRevision: aws
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
