apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: onlineboutique-app
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: anthos
  source:
    path: onlineboutique-app
    repoURL: https://github.com/gft-hybrid-labs/argocd-demo.git
    targetRevision: gcp
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
