apiVersion: v1
kind: Service
metadata:
  labels:
    version: gke
  name: guidewire
  namespace: demo
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8080
  selector:
    app: guidewire
  type: ClusterIP
